name: sup_gen_runner
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

dependencies:
  build: ^2.4.1
  analyzer: '>=5.2.0 <7.0.0'  
  source_gen: ^1.4.0
  sup_gen_model:
    path: ../sup_gen_models
  yaml: ^3.1.2
  collection: ^1.18.0
  glob: ^2.1.2
  path: ^1.9.0
  crypto: ^3.0.6
  dart_style: ^2.3.7
  sup_gen_sqler:
    path: ../sup_gen_sqler
  # path: ^1.8.0

dev_dependencies:
  build_config: ^1.1.1  
  build_runner: ^2.4.6  
  lints: ^2.1.1  
  test: ^1.24.8


