name: copy_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  build: ^2.4.1
  analyzer: '>=5.2.0 <7.0.0'  
  source_gen: ^1.4.0
  # path: ^1.8.0

dev_dependencies:
  build_config: ^1.1.1  
  build_runner: ^2.4.6  
  lints: ^2.1.1  
  test: ^1.24.8
