name: sup_gen_sqler
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  postgres: ^3.4.3
  dartx: ^1.2.0
  sup_gen_model:
    path: ../sup_gen_models
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
